#cloud-config
package_update: true
package_upgrade: true

packages:
  - fail2ban
  - ufw
  - htop
  - wget
  - curl
  - unzip
  - jq

runcmd:
  - ufw allow OpenSSH
  - ufw --force enable
  - systemctl enable fail2ban
  - systemctl start fail2ban
